site:
  title: riddim docs
  url: https://lucienbrule.github.io/riddim
  start_page: development::index.adoc
content:
  sources:
    - url: ..
      branches: HEAD
      start_path: docs/development
    - url: ..
      branches: HEAD
      start_path: docs/user
    - url: ..
      branches: HEAD
      start_path: docs/ops
output:
  dir: build/docs-site
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
